language_flags = {
    'ar': '🇸🇦',
    'bg': '🇧🇬',
    'de': '🇩🇪',
    'el': '🇬🇷',
    'en': '🇬🇧',
    'es': '🇪🇸',
    'fr': '🇫🇷',
    'hi': '🇮🇳',
    'it': '🇮🇹',
    'ja': '🇯🇵',
    'nl': '🇳🇱',
    'pl': '🇵🇱',
    'pt': '🇧🇷',
    'ru': '🇷🇺',
    'sw': '🇹🇿',
    'th': '🇹🇭',
    'tr': '🇹🇷',
    'ur': '🇵🇰',
    'vi': '🇻🇳',
    'zh': '🇨🇳',
}
language_names = {
    'ar': 'Arabic',
    'bg': 'Bulgarian',
    'de': 'German',
    'el': 'Greek',
    'en': 'English',
    'es': 'Spanish',
    'fr': 'French',
    'hi': 'Hindi',
    'it': 'Italian',
    'ja': 'Japanese',
    'nl': 'Dutch',
    'pl': 'Polish',
    'pt': 'Portuguese',
    'ru': 'Russian',
    'sw': 'Swahili',
    'th': 'Thai',
    'tr': 'Turkish',
    'ur': 'Urdu',
    'vi': 'Vietnamese',
    'zh': 'Chinese',
}
sentiment_emojis = {
    'pos': '🙂',
    'neg': '🙁',
    'neu': '😐',
}
sentiment_names = {
    'pos': 'Positive',
    'neg': 'Negative',
    'neu': 'Neutral',
}
